### PR TITLE
Newsweek branch

### PR DESCRIPTION
**Pull request by bafiam**
#### What does this PR do?
Consist on the working code of the project which is a clone of newsweek.com <https://www.newsweek.com/>

#### How should this be manually tested?
Visit the Github pages link on <https://raw.githack.com/bafiam/-Newsweek-clone/newsweek-branch/index.html>

#### NB
 Stickler is showing errors/fail: this is because it is checking the bootstrap local files[bootstrap-4.3.1 ]which i used in the development phase.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi Stephen!  
#### Your project looks :+1:  and very discriptive readme file!
#### But need some Required Changes


Kindly recommended check HTML markup with this validator https://validator.w3.org/#validate_by_upload.

Please check responsiveness of your project. Now each part has little problems. 
For example header on another sizes of screen has space at rightmost side







### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
Project needs changes.

**Comment by bafiam** [comment]
#### What does this PR do?
Consist on the working code of the project which is a clone of newsweek.com <https://www.newsweek.com/>  with TSE review changes

#### How should this be manually tested?
Visit the Github pages link on <https://bafiam.github.io/-Newsweek-clone/>

**Review by suretrust — APPROVED** [review]
Hi @bafiam,

### Amazing job! :raised_hands: Let's get this merged! :+1: 

_Good luck with your future projects and happy coding! :tada:_

**Comment by bafiam** [comment]
hello @Anna-Myzukina  and @suretrust, 

Thanks for your feedback, highly appreciated.

Best Regards

**Pull request merged**
